select * from lines;
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '丹大快速铁路', '丹东-大连');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '沈大高速铁路', '大连-沈阳');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '秦沈客运专线', '沈阳-秦皇岛');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '津秦高速铁路', '秦皇岛-天津');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '津潍高速铁路', '天津-潍坊');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '潍烟高速铁路', '潍坊-烟台');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '青荣城际铁路', '青岛-荣成');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '青盐铁路', '青岛-盐城');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '盐通高速铁路', '盐城-南通');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '沪苏通铁路', '南通-上海');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '沪杭高速铁路', '上海-杭州');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '杭深铁路', '杭州-深圳');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '深茂铁路', '深圳-茂名');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '江湛铁路', '江门-湛江');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '合湛高速铁路', '湛江-合浦');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '钦北铁路', '北海-钦州');
insert into lines(corridor_name, line_name, from_to) values('沿海通道', '钦防铁路', '钦州-防城港');